### PR TITLE
Treat Rise Cache status code 0 as an error

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Can you confirm this is a fix for when Rise Cache makes a request to a 3rd party file that doesn't exist? The request status is `0`, correct?

**Comment by donnapep** [comment]
@stulees Yes, that's correct. This would be the way to tell when a third party file does not exist. Do you recall any other scenarios where the status was 0?

**Comment by stulees** [comment]
@donnapep I don't recall but am surprised that the status is `0` when the 3rd party file doesn't exist. Regardless, seems like a required change :+1:

**Pull request merged**
