### PR TITLE
Fixing custom and google font loading

### PR DESCRIPTION
**Pull request by stulees**
- Custom fonts can't be loaded by WebFontLoader because WebFontLoader needs to target a CSS file, not the font file itself
- Reverted back to `loadCustomFont` function and revised `loadFonts` to load custom fonts via the reverted `loadCustomFont` way
- Ensuring to strip single quotes from google font family name and custom font url
- Ensuring to decode and strip single quotes from custom font family names
- Added and revised test coverage
- Minor version patch bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by donnapep** [comment]
@stulees When I tried loading custom fonts that way, it worked. Does it work for you? Technically you're supposed to load a CSS file, but it was a happy accident when I discovered that it actually doesn't need to be a CSS file. It will load any type of file, including a font file.

**Comment by stulees** [comment]
@donnapep No it didn't work for me. Here's a presentation using production RSS widget set to horizontally scroll with a custom font configured to use for description test. Preview it and the custom font doesn't render. http://rva.risevision.com/#/PRESENTATION_MANAGE/id=5fa1f853-f062-4e8e-9879-e5cb286bc667?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by donnapep** [comment]
@stulees That's weird. It was working at one point. Regardless, maybe it's not the best idea to "hack" WebFontLoader. 👍

**Pull request merged**
