### PR TITLE
Force http protocol for rise cache access

### PR DESCRIPTION
**Pull request by tejohnso**
@stulees please review

### CODE REVIEW

**Comment by stulees** [comment]
@tejohnso You'll need to do a `gulp bump` to bump the version and also run a `gulp build`.

**Comment by tejohnso** [comment]
@stulees gulp build isn't working on my end.   Can you try it on your machine?

Why does the circleci run gulp build if we have to run in locally as well?

**Comment by stulees** [comment]
@tejohnso I'm not sure why `gulp build` doesn't work on your end, what was happening when you tried? 

The circle ci doesn't need to run a gulp build because these files are not being deployed anywhere. It's likely just been configured that way for a long time and runs it mainly for linting purposes. 

I've pushed the necessary files in the last commit. Tests passed locally after my revisions.

**Comment by tejohnso** [comment]
Thanks @stulees.  Okay to merge then?

**Comment by stulees** [comment]
@tejohnso 👍 just need to issue a new release of it after you merge, cheers

**Pull request merged**
