### PR TITLE
Get Player to log events and fallback to BQ directly

### PR DESCRIPTION
**Pull request by stulees**
- Checks existence on top window for `postToPlayer` function and `enableWidgetLogging` flag, if both exist, send log data to player 
- Fallback on usual log to BQ directly

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Since the widget is always within a frame, `top` or `window.top` is a reference to the outermost frame. Cheers

**Comment by rodrigopavezi** [comment]
@stulees cool, thanks for the clarification

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍  cheers

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, cheers

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍  cheers

**Pull request merged**
