### PR TITLE
Upgrading rise-storage version and revising Background module

### PR DESCRIPTION
**Pull request by stulees**
- Upgraded `rise-storage` in bower to latest version `1.0.3`
- Revised `_storageResponse` function in `background.js` to correct event detail usage so it coincides with `rise-storage` upgrade
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by stulees** [comment]
@donnapep FYI, when I tried revising `background-storage.html` to apply the window listener as so:
```
window.addEventListener("polymer-ready", function() {
    gadgets.rpc.register("rsparam_set_" + id, RiseVision.Image.getAdditionalParams);
    gadgets.rpc.call("", "rsparam_get", null, id, ["additionalParams"]);
  });
```
the `rise-storage-mock` never gets used. In other words, adding `go` to the prototype of `HTMLElement` as we have in the `rise-storage-mock` does nothing. I can't really figure out why. When I compare the network requests of documents and source, they're in the exact same order when I include the listener and not include it. So I'm not adding it to the `background-storage.html` test HTML because without it the mock does get used.

**Comment by donnapep** [comment]
@stulees Did you try firing the `polymer-ready` event yourself? There's an example in test/e2e/widget-storage.js in [this PR](https://github.com/Rise-Vision/widget-image/pull/10) for the Image WIdget.

**Comment by stulees** [comment]
@donnapep Ah ha, yes that does the trick. Have done so, review again, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
