### PR TITLE
Change config variables

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees The `config` variable name is causing conflicts with the `config` variable in Video Widget. Please review. Thx.

**Comment by stulees** [comment]
@donnapep There hasn't been a conflict before, it's been necessary for the Widget to specify it's own value - https://github.com/Rise-Vision/widget-video/blob/master/src/config/prod.js#L6 . What impact will this have, will the Widget now need to import `config.js` of widget-common and use `WIDGET_COMMON_CONFIG` object?

**Comment by donnapep** [comment]
@stulees That will only get set if `config` isn't already defined, but it is already defined in `widget-common`, which means neither `SKIN` nor `STORAGE_ENV` will be set. Instead, `STORAGE_ENV` will be `prod`, as defined in `widget-common`, when it should be `test` when running the tests. This is what's causing them to fail in Video Widget.

**Comment by stulees** [comment]
@donnapep The existing integration tests point to the `test.js` config file specifically for this reason - https://github.com/Rise-Vision/widget-video/blob/master/test/integration/widget-video.html#L31 .

**Comment by donnapep** [comment]
@stulees Yes, but I'm loading `components/widget-common/dist/config.js` first, so `STORAGE_ENV` won't be reset by that file you're linking to because this test will resolve to false `if (typeof config === "undefined") {`.

**Comment by stulees** [comment]
@donnapep Okay, that `components/widget-common/dist/config.js` file you're now importing will always be the production built version by widget-common. In the Widget code, will you be using `WIDGET_COMMON_CONFIG` from that file to use its values? If so, how will you override them to build a `dev` or `test` version of the Widget?

**Comment by donnapep** [comment]
@stulees I won't. It will always be Production. The only different between dev / test and prod is STORAGE_ENV, and STORAGE_ENV is only used in background.js. The tests for those pass, and I don't think we're even using this in our Widget settings, are we? If that's true, then I don't think we need to worry about it.

**Comment by stulees** [comment]
@donnapep Okay, I'm just thinking ahead and the possible scenario of needing to override them per widget environment build. So long as the widget-common `config.js` file is imported before the widgets `config.js` file then those `WIDGET_COMMON_CONFIG` values can be overridden. Can you confirm?

**Comment by donnapep** [comment]
@stulees That's correct. If they needed to be overridden they could be further down.

What I'm trying to avoid doing in this PR, and in fact with all of my PRs, is trying to predict things that may happen down the road, because spending time to address a situation that might not ever happen is just wasted effort. I'll admit that this is a rather fine line to walk.

Having said that, if you think this change will break something somewhere else, then that's a problem and I should fix that.

Thx.

**Comment by stulees** [comment]
@donnapep Only Web Page Widget uses the background module, so the next time that Widget needs work and updates its version of widget-common, the Widget will need to account for this change. But I don't see any issues with it. 

Looks good :+1:

**Comment by donnapep** [comment]
@stulees OK, thanks.

**Pull request merged**
