### PR TITLE
Add Widget logging

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep I added a new utils module to move a couple functions into it to help with unit testing. Let me know if you see any more opportunities there.

**Comment by donnapep** [comment]
@stulees I like this. I'm going to start writing some unit tests.

**Comment by donnapep** [comment]
@stulees Are you OK with this PR? If so, I'll merge. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by stulees** [comment]
@donnapep Actually we need a version bump

**Comment by stulees** [comment]
@donnapep Disregard, it was there from the beginning.

**Pull request merged**
