### PR TITLE
Remove use of cachebuster for rise cache module

### PR DESCRIPTION
**Pull request by stulees**
- Removed applying a cachebuster in any situation
- Revised test coverage
- Version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep Double assignment was a mistake, good catch. Have now corrected and also included the missing dist/ files as I had forgotten to run a build. Please review again, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
