### PR TITLE
Use BQ table templates for logging

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi @stulees Please review. Thx.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Actually, this doesn't appear to work. Do you see anywhere I may have gone wrong according to this - https://cloud.google.com/bigquery/streaming-data-into-bigquery#template-tables? Thx.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Figured it out. Table `donna_test` was created as the template table in BQ. Table `donna_test20160105` was created by the logger. Ready for review again. Thx.

**Comment by stulees** [comment]
@donnapep Looks good :+1:

**Pull request merged**
