### PR TITLE
Add widget property to logging

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Also changed the `log` function to accept an object as a parameter. Thx.

**Comment by stulees** [comment]
@donnapep I think you need a version bump, otherwise looks good :+1:

**Comment by donnapep** [comment]
@stulees I deleted the release I had tagged and after I commit will create the release again. Do you know if that will work?

**Comment by stulees** [comment]
@donnapep You need to delete the tag as well, and also your local tag (they persist). Then create a new release/tag after you merge. Should be good after all that.

**Pull request merged**
