### PR TITLE
Don't load fonts in scroller

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi The responsibility for loading fonts is going to fall on the Widget in order to facilitate the use of custom fonts. Please review. Thx.

**Comment by stulees** [comment]
@donnapep Just for my understanding, what is the Widget going to do differently?

**Comment by donnapep** [comment]
@stulees It's going to handle the loading of fonts. More importantly, the Widget font loading functionality already passes CSS class names, which triggers dynamically adding font styles for these classes into the head. Then I'm going to add dummy elements for each of these classes into the Widget HTML in order to force them to download.

**Comment by stulees** [comment]
@donnapep :+1: Okay thanks for clarifying

**Pull request merged**
