### PR TITLE
Adding support for getting a file from Rise Cache

### PR DESCRIPTION
**Pull request by stulees**
- `getFile` function added to RiseCache module for retrieving a file from a 3rd party server
- applicable test coverage
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I think the `getFile` function should handle the ping and the Widget shouldn't need to worry about having to call two functions to get the URL.

Also, there's some minor mixing of double and single quotes.

Thx.

**Comment by stulees** [comment]
@donnapep So what is supposed to be returned in the callback if they are handled in the same function? Are you suggesting `getFile` should return a configured url either way depending on if Rise Cache is running? What if the Widget needs to do something different with the url if Rise Cache is not running?

**Comment by donnapep** [comment]
@stulees How I thought it would work is that the Widget would call `getURL`, passing in the original URL. That function then pings Rise Cache to see if it's running. If it's not, return the original URL unchanged. If it is, make the request to Rise Cache and return the Rise Cache URL.

**Comment by stulees** [comment]
@donnapep I've improved upon the previous version and added further test coverage. `ping()` remains a public function for flexibility. The module now maintains ping received status and if cache is running or not. `getFile()` now conditionally calls ping based on ping received status and configures response based on if cache is running. Also, you can now provide an optional `cachebust` param to `getFile()` if you want a cachebuster added to the url. Please review last commit (I will squash these before merging). Thanks

**Comment by donnapep** [comment]
@stulees I'm not sure I get why you would want to make a call to Rise Cache without a cache buster. Is there currently a scenario where this is needed? If not, then I think the call to Rise Cache should always have one.

**Comment by stulees** [comment]
@donnapep I've changed the param to be `nocachebust` and reversed the logic. So you have to explicitly include the `true` value of `nocachebust` when calling `getFile` if you don't want a cachebuster applied, otherwise it will be applied. Tests updated and I've also squashed/rebased.

**Comment by donnapep** [comment]
@stulees Yup, that works. :+1:

**Pull request merged**
