### PR TITLE
e2e test infrastructure and background e2e tests

### PR DESCRIPTION
**Pull request by stulees**
- adding `web-component-rise-storage` as a dev dependency in bower
- added "clean-bower" and "bower-clean-install" gulp tasks
- gulp file updated with all required e2e tasks
- data mocks added for background storage and url test scenarios
- e2e HTML files added for background storage and url test scenarios
- e2e tests added for background storage and url scenarios
- `background.js` updated to check if `detail` property from the storage response event object is an array or not to apply correct value (this is to appease the rise-storage mock)

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep After a long bout of trial/error, figured out what was wrong with the build. The `circle.yml` file was missing the global install of casperjs in the `pre` section. This fixed it. I happened to notice (in comparison to other repos of ours), that other circle.yml files define the following in `post`:

```
post:
    - bower install
    - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
    - nohup bash -c "java -jar selenium-server-standalone-2.44.0.jar &"
```

The `circle.yml` file in this repo only does the `bower install`. Do you think I should include the other two lines? (it works without them)

**Comment by donnapep** [comment]
@stulees I wouldn't worry about adding those lines. I suspect that other repos don't need them either and they could possibly be removed. Is this ready for review then?

**Comment by stulees** [comment]
@donnapep Yup ready for review

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
