### PR TITLE
[Background] Ensure to remove storage response listener

### PR DESCRIPTION
**Pull request by stulees**
- As a precaution for use of a mock `rise-storage` and their being multiple instances of `<rise-storage>` on a page, now ensuring to remove the "rise-storage-response" listener in the handler function

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I think we should start versioning this repo. Can you do that with this PR?

**Comment by stulees** [comment]
@donnapep Okay I've done the version bump and will tag a release after merging.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
