### PR TITLE
Adding file utility functions to LoggerUtils

### PR DESCRIPTION
**Pull request by stulees**
- `getFileName` and `getFileFormat`  functions, requires file url as the param

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Can we add some negative tests? For example, what happens if the URL is something like `http://www.test.com/`? Also, tests for the URL not being a string or no URL parameter is passed. Thx.

**Comment by donnapep** [comment]
@stulees FYI, files with a URL like this https://www.googleapis.com/storage/v1/b/risemedialibrary-b428b4e8-c8b9-41d5-8a10-b4193c789443/o/Widgets%2Fbig_buck_bunny.mp4?alt=media are coming back with a file format of `mp4?alt=media`.

**Comment by stulees** [comment]
@donnapep Okay, I'm going to revise these functions and test cases, thanks

**Comment by donnapep** [comment]
@stulees Sorry, found another one. This URL `http://localhost:9494/?url=https%3A%2F%2Fstorage.googleapis.com%2Frisemedialibrary-b428b4e8-c8b9-41d5-8a10-b4193c789443%2FWidgets%252FVideo%2520-%2520Issue%252038%252FWildlife.webmsd.webm` returns a file name of `?url=https%3A%2F%2Fstorage.googleapis.com%2Frisemedialibrary-b428b4e8-c8b9-41d5-8a10-b4193c789443%2FWidgets%252FVideo%2520-%2520Issue%252038%252FWildlife.webmsd.webm`.

The encoding is making things complicated, so if you think it's dodgy, maybe we should forget about it.

**Comment by donnapep** [comment]
@stulees I've added `getIds` for getting the Company and Display IDs. Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1: To `getIds`. Regarding `getFileName`, I'm inclined to leave it out. It is getting too complicated given the variation on URLs and encoding. I am going to work on revising `getFileFormat` though and update the tests. A further commit to this PR will be coming.

**Comment by donnapep** [comment]
@stulees Should run it by Alan in that case. Another option is to leave it there since it will be OK in some instances.

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks

**Comment by donnapep** [comment]
@stulees That looks really nice. :+1:

**Pull request merged**
