### PR TITLE
Add function for preloading images

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep It might be worth adding`.onload` listening for each image and an optional param `cb` which could be a function to call when all images have been loaded. Maybe the name of the function could also be `preloadImages`.

**Comment by donnapep** [comment]
@stulees Agreed re: the name. I don't actually need that functionality so perhaps it's best to leave it out until and unless it's needed.

**Comment by donnapep** [comment]
@stulees Updated. Please check. Thx.

**Comment by stulees** [comment]
@donnapep Okay :+1:

**Pull request merged**
