### PR TITLE
Adding Background feature

### PR DESCRIPTION
**Pull request by stulees**
- New `RiseVision.Common.Background` to be used for applying background configuration for a Widget (color and image)
- `background.css` added to provide styling that coincides with the use of `RiseVision.Common.Background`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. Note, this is reliant on elements with ids of `background` and `backgroundStorage` existing in the widget HTML. Thanks

**Comment by donnapep** [comment]
@stulees I think we need to start adding tests to this repo, and I think that now is as good a time as any. What do you think?

**Comment by stulees** [comment]
@donnapep There are some unit tests setup for this already. I had thought to do a unit test for this but then wasn't sure how. It is reliant on the DOM so alternatively I'd need to set up a whole e2e test HTML and infrastructure, which seems overkill. If you know how I could do just a unit test on this I'm open to doing so.

**Comment by donnapep** [comment]
@stulees That's what I mean. I think we need to set up that infrastructure. The alternative is that we have to test the functionality in every single Widget, right? Which is also overkill. I dunno. The goal is that we have to test this. The question is what's the best way of doing so?

**Comment by stulees** [comment]
@donnapep I hear ya. `common.js` has zero test coverage although it's hard to gauge how much of it is really being used by our widgets. 

I agree this repo needs fixing up and full test coverage infrastructure in place with appropriate tests. It's a substantial task though and one suited for a card in backlog for after our current goals. What do you think?

**Comment by donnapep** [comment]
@stulees I think that adding proper test coverage should come before our current goals. It's what Byron has been pushing for for awhile, and I think we are getting to be too focused on our quarterly goals at the expense of proper test coverage. Granted, in certain situations we just can't figure out how to test some pieces, but what's happening is that we're creating bigger and bigger holes in our coverage, and this problem is only compounding the more Widgets we build. So I think we need to take a breather, regroup, and figure out how to plug these holes.

Let's chat more in our meeting.

**Comment by stulees** [comment]
@donnapep Okay, but until so, without passing this PR it leaves me blocked on my current card for Web Page Widget. I have done the majority of work for Background Image Setting integration which subsequently also made me do this PR so that we have a common reusable approach. This is more a reason why I wanted to backlog a card for it so I'm at least not blocked on my current card.

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Cheers. As mentioned, for now, test coverage will be in the Web Page Widget for use of this.

**Pull request merged**
