### PR TITLE
Fix/cross domain 2

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep what do you think about this solution? I think to really check if a file exists on preview without the disturbance of cross domain issues we will have to create a proxy service for it. With this solution we at least show the right message on the player but does not break the preview of video files with no CORS.  cheers

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi Looks promising. Do you think it's possible to add tests for the `onerror` handler?

**Comment by rodrigopavezi** [comment]
@donnapep sure, I will try adding tests for it. cheers

**Comment by rodrigopavezi** [comment]
@donnapep I could not find a way to trigger the onerror. One attempt was to trigger a timeout but it didn't work.

```javascript
describe("getFile - timeout", function () {
    var riseCache = RiseVision.Common.RiseCache,
      xhr, clock, requests;

    before(function() {
      xhr = sinon.useFakeXMLHttpRequest();
      clock = sinon.useFakeTimers();

      xhr.onCreate = function (xhr) {
        requests.push(xhr);
      };
    });

    beforeEach(function() {
      requests = [];

      riseCache.ping(function(){});
      requests[0].respond(400);
    });

    after(function() {
      xhr.restore();
      clock.restore();
    });

    it("should execute callback passing the xhr request and a correctly structured URL with no cachebuster", function() {
      var spy = sinon.spy();

      riseCache.getFile("http://www.test.com/test.jpg", spy, true);
      
      clock.tick(20*60*60*1000);

      expect(spy.args[0][0].xhr).to.deep.equal(requests[1]);
      expect(spy.args[0][0].url).to.equal("http://www.test.com/test.jpg");
      expect(spy.args[0][1].message).to.equal("The request failed with no status");
    });

  });
``` 

I will have to leave it without a test.
cheers

**Comment by donnapep** [comment]
@rodrigopavezi OK, was thinking it would be problematic. I think we'll have to do some manual validation for this one to be sure. :+1:

**Comment by rodrigopavezi** [comment]
@donnapep yeap, agreed. cheers

**Pull request merged**
